package View;

import Model.Hotel;
import Model.Room;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex
 */
public class HotelForm extends javax.swing.JFrame {
    private static ArrayList<Room> herbergi;
    private static ArrayList<Hotel> hotel;
    private static ArrayList<Date> dates;
    private int sida;
    /**
     * Creates new form HotelForm
     * @param room
     * @param hotel
     * @param dates
     */

    public HotelForm(ArrayList<Room> room, ArrayList<Hotel> hotel, ArrayList<Date> dates) throws IOException {

        initComponents();
        HotelForm.herbergi = room;
        HotelForm.hotel = hotel;
        HotelForm.dates = dates;
        sida = 1;stillaSidu();
        fyrra.setEnabled(false);
        stillaSidu();
    }
    
    public void setHerbergi(ArrayList<Room> herbergi) {
        this.herbergi = herbergi;
    }
    
    public void setHotel (ArrayList<Hotel> hotel) {
        this.hotel = hotel;
    }
    
    public void stillaSidu() throws IOException {
        if(hotel == null) throw new IllegalArgumentException("Upphafstilla þarf hótel!");
        else {
            stillaConv();
            stillaMynd();
            stillaNafn();
            stillaStjornur();
            stillaStads();
            stillaNR();
        }
    }
    private void stillaNR() {
        stadsSida.setText(sida + "/" + hotel.size());
    }
    
    private void stillaMynd() throws MalformedURLException, IOException {
        Hotel theHotel = hotel.get(sida);
        String photo = theHotel.getPhoto_URL();
        URL url = new URL(photo);
        Image image = ImageIO.read(url);
        myndLabel.setIcon(new ImageIcon(image));
    }
    
    private void stillaStads() {
        Hotel theHotel = hotel.get(sida);
        String stads = theHotel.getLocation();
        nafnStadsetning.setText(stads);
    }
    
    private void stillaStjornur() {
        Hotel theHotel = hotel.get(sida);
        int stars = theHotel.getStars();
        if(stars == 1) {
            hotelStjornur.setText("*");
        }else if(stars == 2) {
            hotelStjornur.setText("**");
        }else if(stars == 3) {
            hotelStjornur.setText("***");
        }else if(stars == 4) {
            hotelStjornur.setText("****");
        }else if(stars == 5) {
            hotelStjornur.setText("*****");
        }
    }
    
    private void stillaNafn() {
        Hotel theHotel = hotel.get(sida);
        String name = theHotel.getName();
        heitiHotel.setText(name);
    }
    
    private void stillaConv() {
        Hotel theHotel = hotel.get(sida);
        String[] convinience = theHotel.getConveniences();
        for(int i = 0; i < convinience.length; i++) {
            if(i == 0) {
                conv0.setText(convinience[i]);
            }else if(i == 1) {
                conv1.setText(convinience[i]);
            }else if(i == 2) {
                conv2.setText(convinience[i]);
            }else if(i == 3) {
                conv3.setText(convinience[i]);
            }else if(i == 4) {
                conv4.setText(convinience[i]);
            }else if(i == 5) {
                conv5.setText(convinience[i]);
            }else if(i == 6) {
                conv6.setText(convinience[i]);
            }else if(i == 7) {
                conv7.setText(convinience[i]);
            }else if(i == 8) {
                conv8.setText(convinience[i]);
            }else if(i == 9) {
                conv9.setText(convinience[i]);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heitiHotel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        skodaHerb = new javax.swing.JButton();
        stadsSida = new javax.swing.JLabel();
        haettaVid = new javax.swing.JButton();
        fyrra = new javax.swing.JButton();
        naesta = new javax.swing.JButton();
        stadsetning = new javax.swing.JLabel();
        nafnStadsetning = new javax.swing.JLabel();
        myndLabel = new javax.swing.JLabel();
        conv1 = new javax.swing.JLabel();
        conv0 = new javax.swing.JLabel();
        conv = new javax.swing.JLabel();
        conv3 = new javax.swing.JLabel();
        conv4 = new javax.swing.JLabel();
        conv2 = new javax.swing.JLabel();
        conv5 = new javax.swing.JLabel();
        conv6 = new javax.swing.JLabel();
        conv7 = new javax.swing.JLabel();
        conv8 = new javax.swing.JLabel();
        stjornur = new javax.swing.JLabel();
        hotelStjornur = new javax.swing.JLabel();
        conv9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(75, 119, 190));

        heitiHotel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        heitiHotel.setText("heitiHotel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heitiHotel)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(heitiHotel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 60);

        jPanel2.setBackground(new java.awt.Color(228, 241, 254));

        skodaHerb.setText("Look at rooms");
        skodaHerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skodaHerbActionPerformed(evt);
            }
        });

        stadsSida.setText("3/4");

        haettaVid.setText("Cancel");
        haettaVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haettaVidActionPerformed(evt);
            }
        });

        fyrra.setText("Previous");
        fyrra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fyrraActionPerformed(evt);
            }
        });

        naesta.setText("Next");
        naesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naestanaestButton(evt);
            }
        });

        stadsetning.setText("Location:");

        nafnStadsetning.setText("nafnStadsetning");

        conv1.setText("conv3");

        conv0.setText("conv1");

        conv.setText("Conveniences:");

        conv3.setText("conv2");

        conv4.setText("conv4");

        conv2.setText("conv5");

        conv5.setText("conv6");

        conv6.setText("conv7");

        conv7.setText("conv8");

        conv8.setText("conv9");

        stjornur.setText("Stars:");

        hotelStjornur.setText("hotelStjornur");

        conv9.setText("conv0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(stadsSida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skodaHerb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(haettaVid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fyrra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naesta)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(myndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(conv7)
                        .addGap(18, 18, 18)
                        .addComponent(conv8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stadsetning)
                            .addComponent(stjornur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotelStjornur)
                            .addComponent(nafnStadsetning)))
                    .addComponent(conv)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(conv9)
                        .addGap(18, 18, 18)
                        .addComponent(conv0)
                        .addGap(18, 18, 18)
                        .addComponent(conv3)
                        .addGap(18, 18, 18)
                        .addComponent(conv1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(conv4)
                        .addGap(18, 18, 18)
                        .addComponent(conv2)
                        .addGap(18, 18, 18)
                        .addComponent(conv5)
                        .addGap(18, 18, 18)
                        .addComponent(conv6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nafnStadsetning)
                            .addComponent(stadsetning))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stjornur)
                            .addComponent(hotelStjornur))
                        .addGap(18, 18, 18)
                        .addComponent(conv)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conv9)
                            .addComponent(conv0)
                            .addComponent(conv3)
                            .addComponent(conv1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(myndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conv2)
                    .addComponent(conv4)
                    .addComponent(conv5)
                    .addComponent(conv6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conv7)
                    .addComponent(conv8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skodaHerb)
                    .addComponent(stadsSida)
                    .addComponent(haettaVid)
                    .addComponent(fyrra)
                    .addComponent(naesta))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 460, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void naestanaestButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naestanaestButton
        try {
            // TODO add your handling code here:
            naestaSida();
        } catch (IOException ex) {
            Logger.getLogger(HotelForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_naestanaestButton

    private void fyrraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fyrraActionPerformed
        try {
            // TODO add your handling code here:
            fyrriSida();
        } catch (IOException ex) {
            Logger.getLogger(HotelForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fyrraActionPerformed

    private void haettaVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haettaVidActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_haettaVidActionPerformed

    private void skodaHerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skodaHerbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skodaHerbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HotelForm(herbergi, hotel, dates).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(HotelForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conv;
    private javax.swing.JLabel conv0;
    private javax.swing.JLabel conv1;
    private javax.swing.JLabel conv2;
    private javax.swing.JLabel conv3;
    private javax.swing.JLabel conv4;
    private javax.swing.JLabel conv5;
    private javax.swing.JLabel conv6;
    private javax.swing.JLabel conv7;
    private javax.swing.JLabel conv8;
    private javax.swing.JLabel conv9;
    private javax.swing.JButton fyrra;
    private javax.swing.JButton haettaVid;
    private javax.swing.JLabel heitiHotel;
    private javax.swing.JLabel hotelStjornur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel myndLabel;
    private javax.swing.JButton naesta;
    private javax.swing.JLabel nafnStadsetning;
    private javax.swing.JButton skodaHerb;
    private javax.swing.JLabel stadsSida;
    private javax.swing.JLabel stadsetning;
    private javax.swing.JLabel stjornur;
    // End of variables declaration//GEN-END:variables

      private void naestaSida() throws IOException {
        sida++;
        if(sida==hotel.size()) naesta.setEnabled(false);
        if(sida==2) fyrra.setEnabled(true);
        stillaSidu();
    }

    private void fyrriSida() throws IOException {
        sida--;
        if(sida==1) fyrra.setEnabled(false);
        stillaSidu();
    }

}