/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author Notandi
 */
public class SearchForm extends javax.swing.JFrame {

    boolean checkBoxes[];
    /**
     * Creates new form Search
     */
    public SearchForm() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSearch = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jCheckBoxWiFi = new javax.swing.JCheckBox();
        jCheckBoxMorgunmatur = new javax.swing.JCheckBox();
        searchButton = new javax.swing.JButton();
        jCheckBoxMidbae = new javax.swing.JCheckBox();
        jCheckBoxTv = new javax.swing.JCheckBox();
        jCheckBoxSturta = new javax.swing.JCheckBox();
        jCheckBoxAirport = new javax.swing.JCheckBox();
        jCheckBoxSpa = new javax.swing.JCheckBox();
        jCheckBoxLikamsraekt = new javax.swing.JCheckBox();
        jCheckBoxGonguleid = new javax.swing.JCheckBox();
        jCheckBoxFotlun = new javax.swing.JCheckBox();
        jButtonInnskraning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSearch.setText("Hotel name:");

        jCheckBoxWiFi.setText("Frítt wi-fi");

        jCheckBoxMorgunmatur.setText("Morgunmatur innifalinn");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jCheckBoxMidbae.setText("Nálægt miðbæ");

        jCheckBoxTv.setText("Tv");

        jCheckBoxSturta.setText("Sturta");

        jCheckBoxAirport.setText("Airport pickup/drop off");

        jCheckBoxSpa.setText("Spa");

        jCheckBoxLikamsraekt.setText("Líkamsrækt");

        jCheckBoxGonguleid.setText("Göngu/Hjólaleiðir");

        jCheckBoxFotlun.setText("Aðstaða fyrir fólk með fötlun");

        jButtonInnskraning.setText("Innskráning");
        jButtonInnskraning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInnskraningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxFotlun)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxAirport)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSearch)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBoxLikamsraekt)
                                    .addComponent(jCheckBoxWiFi)
                                    .addComponent(jCheckBoxGonguleid))
                                .addGap(59, 59, 59)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMorgunmatur)
                            .addComponent(jCheckBoxSpa)
                            .addComponent(jCheckBoxSturta)
                            .addComponent(jCheckBoxTv)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonInnskraning)
                                .addComponent(jCheckBoxMidbae)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearch)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFotlun)
                    .addComponent(jCheckBoxMorgunmatur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAirport)
                    .addComponent(jCheckBoxMidbae))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCheckBoxWiFi))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSpa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxGonguleid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxLikamsraekt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(jButtonInnskraning))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxSturta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTv)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        checkBoxes = new boolean[] {
            jCheckBoxFotlun.isSelected(), jCheckBoxAirport.isSelected(), jCheckBoxWiFi.isSelected(), jCheckBoxGonguleid.isSelected(), jCheckBoxLikamsraekt.isSelected(), 
            jCheckBoxMorgunmatur.isSelected(), jCheckBoxMidbae.isSelected(), jCheckBoxSpa.isSelected(), jCheckBoxSturta.isSelected(), jCheckBoxTv.isSelected()
        };
        String[] queries = {"Fotlun", "Airport", "Wi-fi", "Gonguleid", "Likamsraekt", "Morgunmatur", "Midbaer", "Spa", "Sturta", "Tv"};
        String searchString = jTextFieldSearch.getText();
        String query = "";
        for (int i = 0; i < 10; i++) {
            if (checkBoxes[i] == true) {
                query += " AND conveniences LIKE '%" + queries[i] + "%'";
            }
        }
        Connection connection = null;
        try {
            connection = DriverManager.getConnection("jdbc:sqlite:C:/Users/Notandi/Documents/Skóli/Þróun Hugbúnaðar/ThrounHugbunadar/Hoteldb.db");
            Statement statement = connection.createStatement();
            statement.setQueryTimeout(30);
            //statement.executeUpdate("insert into table values(1,2)");
            ResultSet rs = statement.executeQuery("SELECT * from Hotel where name like '%" + searchString + "%'" + query);
            //System.out.print("SELECT * from Hotel where name like '%" + searchString + "%'" + query);
            while(rs.next()) {
                String strLine = rs.getString("conveniences");
                String[] conveniences = strLine.split(":");
                System.out.println("Hotelið heitir " + rs.getString("name"));
                System.out.println("Staðsetningin er " + rs.getString("location"));                
                for (String convenience : conveniences) {
                    System.out.println("Hótelið inniheldur: " + convenience);
                }
            }
        }
        catch(SQLException e) {
            System.err.println(e.getMessage());
        }
        finally
        {
          try
          {
            if(connection != null)
              connection.close();
          }
          catch(SQLException e)
          {
            // connection close failed.
            System.err.println(e);
          }
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButtonInnskraningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInnskraningActionPerformed
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonInnskraningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInnskraning;
    private javax.swing.JCheckBox jCheckBoxAirport;
    private javax.swing.JCheckBox jCheckBoxFotlun;
    private javax.swing.JCheckBox jCheckBoxGonguleid;
    private javax.swing.JCheckBox jCheckBoxLikamsraekt;
    private javax.swing.JCheckBox jCheckBoxMidbae;
    private javax.swing.JCheckBox jCheckBoxMorgunmatur;
    private javax.swing.JCheckBox jCheckBoxSpa;
    private javax.swing.JCheckBox jCheckBoxSturta;
    private javax.swing.JCheckBox jCheckBoxTv;
    private javax.swing.JCheckBox jCheckBoxWiFi;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
